#!/usr/bin/python -B

import os
import sys

def solve_imports(path, folders):
    if not path in sys.path:
        sys.path.insert(0, path)
        for folder in folders:
            path = os.path.join(path, folder)
            if not path in sys.path:
                sys.path.insert(0, path)


path = os.path.abspath(os.path.dirname(sys.argv[0]))

path = os.path.join(path, '..')
folders = ['algorithms']
solve_imports(path, folders)

path = os.path.join(path, 'src')
folders = ['lib']
solve_imports(path, folders)



if not path in sys.path:
    sys.path.insert(0, path)
    for folder in folders:
        path = os.path.join(path, folder)
        if not path in sys.path:
            sys.path.insert(0, path)






from gui.main import Main
from lib import config, system, logger

if __name__ == "__main__":
    # configure logging
    logger = logger.Logger()

    # configuration file
    config = config.Config()
    logger.info("Starting GUI..")
    grape = Main()

    # saving config changes and reference values
    # config.save()
