#! /bin/sh


path = os.path.abspath(os.path.dirname(sys.argv[0]))
rm app/views/*.h


intltool-extract --type=gettext/glade ../gui/*.ui
xgettext --language=Python --keyword=_ --keyword=N_ --output=default.pot ../app/view/  ../*.py ../gui/*.py ../gui/*.h ../lib/*.py
msginit --input=default.pot --locale=pt_BR
rm ../app/views/*.h


mkdir -p pt_BR/LC_MESSAGES
msgfmt --output-file=pt_BR/LC_MESSAGES/grape.mo pt_BR.po

